apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: hanoguz00/mlops_ingress_v1
          ports:
            - containerPort: 8000
          env:
            - name: SQLALCHEMY_DATABASE_URL
              value: "postgresql://postgres:postgres@postgres/postgres"
